### PR TITLE
fix: Enabled category creation

### PR DESCRIPTION
**Pull request by Larsluph**
# Enabled category creation [fix]

Removed return statement that blocked category creation action

# PR Checklist

- [x] I've started from master
- [x] I've only committed changes related to this PR
- [x] All Unit tests pass
- [x] I've removed all commented code
- [x] I've removed all unneeded console.log statements

### CODE REVIEW

**Comment by WDaan** [comment]
😬 good catch... lack of proper tests makes things like this slip through. 

Must've forgotten when improving the validation. 

Shouldn't it still early return when validation is falsy though? By removing the return it will probably still continue.

**Review by WDaan — APPROVED** [review]

**Comment by Larsluph** [comment]
Now that you say it that may be a good thing to test, i'll check that!

**Comment by Larsluph** [comment]
Okay so I checked that validation method and it's useless as-is. With that, I removed the length limitations which are not present in the qBittorrent WebUI API.

**Comment by WDaan** [comment]
Awesome! 

The 2 translations can be cleaned up as well.


Don't know why the limit was introduced in the first place.

**Comment by Larsluph** [comment]
FYI, certain translation mappings are missing some keys: es, it, nl, pt-br, vi

**Comment by WDaan** [comment]
I know, but I'm not able to translate those. So, depending on the community.

**Comment by Larsluph** [comment]
Maybe you can add a segment on that in the readme ?

**Comment by WDaan** [comment]
That's a good idea. 
I'm also trying to find a tool that can show which translations are missing in the other files, but haven't found exactly what I'm looking for just yet.

**Pull request merged**
