### PR TITLE
feat: auto releasing ci

### PR DESCRIPTION
**Pull request by jef**
### Description

I know there are a lot of changes and may warrant a bit of speculation, but I will try elaborate on what's going on here in a list below.

- Introduces new action `google-github-actions/release-please-action`
    - I love this action because it manages releases for you.
    - Keeps a `CHANGELOG` based on [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/). This isn't necessary, but is cool feature.
    - Auto updates PR for next version.
    - You merge the PR when you're ready for release.
    - This means you push to master every commit and only when you merge the PR, it creates release assets and pushes to your `latest-release` branch (more on this later).
    - This includes auto updating the version in `package.json`.
- Uploading release assets
    - Nothing really new here, but removes unnecessary zip action.
    - Changes zip name to be `vuetorrent.zip` rather than `release.zip`.
- Pushes release automatically to `latest-release`
    - This part is sort of deceiving in the code because of the action name (JamesIves/github-pages-deploy-action). I have used this action in the past for GitHub pages, but this a great action for this use case.
    - What will happen is when we merge the release please PR, this action will build the project and publish to the branch, as it current is now (without a `README`). But we can easily update the project's `README`, to show how to use branch.
- Changed when tests run
    - Nothing too crazy here, basically the same thing. But it makes sense to only run tests during pushes to `master` and pull requests to `master` in my opinion.

---

Kind of did this on a whim, but figured it would be really good to have something easier to manage!

Take a look at one of my repos and see how it publishes:

- https://github.com/jef/streetmerchant (quite a bit of CHANGELOG and other things in this one)
- https://github.com/jef/stargazer-vanity (shows how release asset is used)

Feel free to ask any questions!

### CODE REVIEW

**Comment by WDaan** [comment]
Amazing! This is what I've been wanting/looking for for a long time and more!
I would need to test a little before I implement it.

2 Questions:
1) How does it know when to increment a major version number?
2) The workflow seems to run on every push on master, how does it know when to actually release?

**Comment by jef** [comment]
> 1. How does it know when to increment a major version number?

Firstly, the versions get bumps based on the commit messages. In this case, that would mean PR titles since we use squash and merge method here (which is best is great!). That being said, there are two ways. One is using the main commit message or using the commit body:

- **PR Title**: `<type>(optional scope)!: <some message>`
    - `feat: changed something` (minor bump)
    - `changed something` (patch bump, I think, not entirely sure)
    - `feat!: changed something` (major bump)
    - `ci: changed something` (no bump)
    - `docs: changed something` (no bump)
**PR Body** _(during commit)_:

```
- This adds/changes something
- This adds/changes something

BREAKING CHANGE: This changed
```

image

Only for major bumps, the commit (PR) body will do this. I usually just use the former.

You can see more on this [here](https://github.com/google-github-actions/release-please-action#how-should-i-write-my-commits).

**Comment by jef** [comment]
Also, if this gets merged in, I don't mind being on stand by to ensure everything goes smoothly. You just let me know what else you need from me and I can provide some examples or explanations!

**Comment by jef** [comment]
I can update the README as well since _some_ of the installation will change. Mostly just naming.

**Comment by WDaan** [comment]
Thanks!

I think the only changes are the name of the .zip & the path of the latest-release branch. It seems like you directly upload what's inside of the public folder. Very smart utilisation of the github-pages action BTW!

Also, I think that de README in the latest-release branch will disappear on a new release?

**Comment by jef** [comment]
> Also, I think that de README in the latest-release branch will disappear on a new release?

Yep! Thanks right.

**Comment by jef** [comment]
Okay! I think it's good to go. Let me know if you need anything else.

**Comment by WDaan** [comment]
I also wanted to remove the old release script in this PR, but its kind off related

**Comment by jef** [comment]
Great. Thanks for doing it. Commit looks great too :wink:

**Comment by WDaan** [comment]
No, thank you! This is a big step in the right direction. It shows that the project is maturing a little bit.
Also decreases the risk of human errors etc

**Comment by jef** [comment]
The workflows help a _ton_. I'll make a comment on the PR that gets created after this merged is merged.

**Comment by WDaan** [comment]
There seems to be a small mistake somewhere in both workflows

**Comment by jef** [comment]
Oh whoops. Thank you!

**Pull request merged**
