### PR TITLE
Add globalSpeed and globalVolume computed values to torrent properties

### PR DESCRIPTION
**Pull request by Larsluph**
# Add globalSpeed and globalVolume computed values to torrent properties [feat]

Compute global values (sum of download and upload) for transfer volume and transfer speed.

# PR Checklist

- [x] I've started from master
- [x] I've only committed changes related to this PR
- [x] All Unit tests pass
- [x] I've removed all commented code
- [x] I've removed all unneeded console.log statements

### CODE REVIEW

**Comment by WDaan** [comment]
Could you explain this feature a little bit more please? I'm not quite sure I follow

**Comment by Larsluph** [comment]
The only "useful" diff in this Pr are these : https://github.com/WDaan/VueTorrent/pull/599/files#diff-df87f1db7ad372d7981cd494af44c6f1934a6eaf30f2fa19fee4334a3cd32407R49-R52

I just added a torrent property to be able to display and sort by the total bandwidth used by a single torrent (globalSpeed), I also added globalVolume because it's literally the same thing

**Comment by WDaan** [comment]
Aha! I understand, neat 😎 

Ready to merge?

**Comment by WDaan** [comment]
Thanks for checking 😃

**Comment by Larsluph** [comment]
I need your advice @WDaan for the design of this fix
To disable sorting using the API, is it better to
- Create an array with the name of the properties to exclude
- Use a prefix (like `computedGlobalSpeed`) and disable it if the property name starts with `computed`

Knowing that I plan to improve the feature by adding a local sorting system where everything is handled on our end (which may allow for better sorting customisation)

**Comment by WDaan** [comment]
I guess an array because it allows for greater flexibility later on?

**Comment by Larsluph** [comment]
Everything should work now! 🚀

**Pull request merged**
