### PR TITLE
fix: build errors

### PR DESCRIPTION
**Pull request by Larsluph**
# Fix build errors [fix]

# PR Checklist

- [x] I've started from master
- [x] I've only committed changes related to this PR
- [x] All Unit tests pass
- [x] I've removed all commented code
- [x] I've removed all unneeded console.log statements

### CODE REVIEW

**Comment by WDaan** [comment]
Not really sure what the goal for this is?

**Comment by Larsluph** [comment]
I was just testing the action not working you don't have to merge it right now 😉

**Comment by Larsluph** [comment]
This one should build correctly ^^

**Comment by Larsluph** [comment]
And I don't know if that's normal but I noticed that no actions are triggered on PRs compared to the master branch...

**Pull request closed without merging**
