### PR TITLE
perf: Register magnet handler

### LINKED ISSUE #111: [Feature Request] register and work with magnet link handler
The original web UI has a function to automatically register mailto links to qBittorrent.

Once registered, your browser will try to redirect to qbittorrent appending `/#/download/` + the URL encoded magnet link:
grafik

grafik

Feature Request:
* Allow vuetorrent to work with the qbittorrent magnet link handler
* Offer a button in vuetorrent to register the current UI for the magnet link handler

Should be straightforward and is the only major flaw with this web interface! 😁

### LINKED ISSUE #781: Register to handle magnet links option is missing
In the default theme there's an option to associate the webui as the default app for magnet urls. This option is missing from your theme (or I'm blind and I just can't find it).
Also if there's a way to also associate with .torrent files that'd be neat.

### PR DESCRIPTION
**Pull request by Larsluph**
# Register magnet handler [perf]

Adds a button in the settings view to register magnet handler.

source: https://github.com/qbittorrent/qBittorrent/blob/cddf8c199cdc364548e2ca827ae37e92476515cd/src/webui/www/private/scripts/client.js#L1404-L1423

# PR Checklist

- [x] I've started from master
- [x] I've only committed changes related to this PR
- [x] All Unit tests pass
- [x] I've removed all commented code
- [x] I've removed all unneeded console.log statements

Fixes #111
Fixes #781

### CODE REVIEW

**Comment by WDaan** [comment]
Need any help with this? 

What this blocking? :)

**Comment by Larsluph** [comment]
Nothing, I just didn't tested the feature and it requires a secured context. I'm just waiting to get back home to test it on my home qbit.

**Comment by Larsluph** [comment]
And I also need to update the snapshot 😅

**Comment by WDaan** [comment]
Sure, have fun :)

**Comment by WDaan** [comment]
Lets find out if this works 😄

**Pull request merged**
