### PR TITLE
Datatable view for torrents on desktop version

### PR DESCRIPTION
**Pull request by WDaan**
Looks great! @Ov3r1d3

This could easily be implemented as a user setting :slightly_smiling_face:

### CODE REVIEW

**Comment by Ov3r1d3** [comment]
Thanks !!!,
I really liked the repository in the first place , when I saw it and I like
that it was written on Vue.
I will make some changes , since it was pretty fast written and will make a
pull request
Regards,
Stelios


Στις Πέμ, 4 Φεβ 2021 στις 5:08 μ.μ., ο/η Daan Wijns <
notifications@github.com> έγραψε:

**Comment by WDaan** [comment]
Great! I really appreciate you contributing to this project.

Your table view is waaay better if you have lots & lots of torrents.

**Comment by mrhotio** [comment]
> Your table view is waaay better if you have lots & lots of torrents.

My thoughts exactly, great job to the both of you...any idea when we might get to see this merged?

**Comment by LukePrior** [comment]
@Ov3r1d3 is this still being developed?

**Comment by WDaan** [comment]
I don't think so, we'll probably need to write our own implementation

**Comment by Mehdib92** [comment]
Hi,
Any idea if this view will be release in the future ?

**Comment by WDaan** [comment]
It will be implemented, I really want to have this! But I can't give you an ETA. We haven't started on this yet & I don't think I'll find the time anytime soon 😐

**Comment by Mehdib92** [comment]
Thank you for your work

**Comment by giacomocerquone** [comment]
uuuh great work here!

**Comment by WDaan** [comment]
Closing but keeping #157 open, will still try to implement this.

**Pull request closed without merging**
