### PR TITLE
perf: Rework desktop cards

### PR DESCRIPTION
**Pull request by Larsluph**
# Rework desktop cards [perf]

Add flex gap to Desktop Card to improve item separation lisibility and reworked margins.

# PR Checklist

- [x] I've started from master
- [x] I've only committed changes related to this PR
- [x] All Unit tests pass
- [x] I've removed all commented code
- [x] I've removed all unneeded console.log statements

### CODE REVIEW

**Comment by WDaan** [comment]
Still trying to convert the components? 😝

Seems like most things are working except the one test, probably some small mistake with the status constructor (expoter?)

**Comment by Larsluph** [comment]
Yup I'm converting the components when I need to change things in them. I'm trying to fix that error but I really don't understand what's the issue 😅

**Comment by WDaan** [comment]
As for the `helpers.js` you can convert it to `.ts` maybe into a seperate folder so you can split up the helpers.

```
export function getVersion() {
  if (isProduction()) {
    return 'import.meta.env.VITE_PACKAGE_VERSION'
  }

  return import.meta.env['VITE_PACKAGE_VERSION']
}

export function getBaseURL() {
  if (isProduction()) {
    return 'import.meta.env.BASE_URL'
  }

  return import.meta.env['BASE_URL']
}
```

These ones that are giving issues, we can keep in a `.js` for now, will solve later.

**Comment by WDaan** [comment]
Looking into the failing test, not sure yet why it isn't working

**Comment by Larsluph** [comment]
For the helpers, I still got the parse error when I'm separating things

**Comment by WDaan** [comment]
replacing `this.$i18n.t` by `this.$t` seems to have made it better 😛

**Comment by Larsluph** [comment]
Insane, seems like I will never understand JS sometimes 😂
Good job!

**Pull request merged**
