### PR TITLE
Change the context menu mechanism

### PR DESCRIPTION
**Pull request by m4ximuel**
# Features
- Right-click menu available for iPhone and most devices. Replaced by Long Touch
# Fixes
- Removed 'context-menu' package that is no longer available

### CODE REVIEW

**Comment by WDaan** [comment]
This context menu is insane!! I really like it, makes it way easier to use.
On mobile the transition speed should be a little faster I think, it feels a tad sluggish

**Comment by m4ximuel** [comment]
@WDaan Standard milliseconds for user response. Would it be okay to adjust it to 500ms->400ms?
Also, there is a problem with opening the sub-menu on mobile, so I'm in the process of adjusting.

**Comment by WDaan** [comment]
Sure, maybe even 300ms... as long as it feels responsive.

What seems to be the issue?? I tested it and for me it worked perfectly fine :)

**Comment by m4ximuel** [comment]
@WDaan 
When the touch mode is detected, the menu is not closed when the sub-menu is clicked.
:open-on-hover="!touchmode"
Greater compatibility.

**Comment by m4ximuel** [comment]
@300ms, ok

**Comment by m4ximuel** [comment]
merge to #207

**Pull request closed without merging**
