### PR TITLE
Control content tab use keyboard

### PR DESCRIPTION
**Pull request by m4ximuel**
# Control content tab use keyboard [feat]
- Move the list index with the up and down arrow keys
- Expand/collapse the list with the left and right arrow keys
- Toggle exclude/include files with space and enter keys

# PR Checklist
- [x] I've started from master
- [x] I've only committed changes related to this PR
- [x] All Unit tests pass
- [x] I've removed all commented code
- [x] I've removed all unneeded console.log statements

### CODE REVIEW

**Comment by m4ximuel** [comment]
@WDaan I thought I made a PR from the 'master', but there is an unexpected history. Shall I make a new PR?

**Comment by WDaan** [comment]
No it's fine :) it only shows changes related to this PR. That's what matters.

I will test this out tomorrow! It looks impressive.

**Comment by m4ximuel** [comment]
I found a bug in the treeview.
Items with the same file name are not selected at the same time, but items with the same folder name are selected at the same time. Please solve this problem.

**Comment by m4ximuel** [comment]
@WDaan Functionally, it is complete, but please review whether that part of the bug is a fixable problem. I can't modify the treeview structure because it can't be interpreted.

**Comment by WDaan** [comment]
What do you mean by "it can't be interpreted"?

**Comment by m4ximuel** [comment]
> What do you mean by "it can't be interpreted"?

I don't know how to edit tree data.

**Comment by WDaan** [comment]
The 'tree' is generated with the treeify function. Once it's generated and passed into component, you cant do much with it anymore.

That's why I would like to get rid of the v-treeview component & look for another solution. One where we have more control over what happens

**Comment by m4ximuel** [comment]
@WDaan hmm... Could you fix the first bug I mentioned before looking for a another solution?

> Items with the same file name are not selected at the same time, but items with the same folder name are selected at the same time.

It's out of my abilities. I can hardly understand the treeview.
Once you fix this, #60 can be closed satisfactorily.
Something... It seems to be possible to use the difference between the data included in the 'file' and the 'folder', but...

**Comment by WDaan** [comment]
Closed due to inactivity

**Pull request closed without merging**
