### PR TITLE
chore: Added testcase for Plugin Manager

### PR DESCRIPTION
**Pull request by NitinRamnani**
# My Title [feat/fix/perf/chore]

Added testcase for Plugin Manager Component and improved code coverage

image

# PR Checklist

- [x] I've started from master
- [x] I've only committed changes related to this PR
- [x] All Unit tests pass
- [x] I've removed all commented code
- [x] I've removed all unneeded console.log statements

### CODE REVIEW

**Comment by WDaan** [comment]
Hi! Thanks for contributing to this project.

Your tests fails in CI though? How did you get it to work locally?

Also, you should be able to use `.ts` 😄

**Comment by NitinRamnani** [comment]
That's strange on local testcases are passing and since existing testcases are in js that's why I added new file in js.

**Comment by WDaan** [comment]
Could it be that you're local branch is severely out of date? Please merge master into it && you should start seeing it fail locally as well.

**Comment by NitinRamnani** [comment]
You were correct my copy of repo was out of date. Nice catch 🙌. Fixed the issue.

**Comment by WDaan** [comment]
Want me to add any Hacktober labels or anything?

**Comment by NitinRamnani** [comment]
No, since repo has label "hacktoberfest" no additional label is required on PRs.

**Pull request merged**
