### PR TITLE
AddTrackers dialog bug fix

### PR DESCRIPTION
**Pull request by m4ximuel**
Does not close after clicking close. There is a problem with the declaration.

# Fixes
- AddTrackers dialog bug fix

### CODE REVIEW

**Comment by WDaan** [comment]
I can't seem to reproduce this?  For me the cancel button works just fine?

image

**Comment by m4ximuel** [comment]
> I can't seem to reproduce this? For me the cancel button works just fine?
> 
> image

Existing source code shares the same function 'addTrackers' for 'cancel' and 'add'. And the definition for 'dialog' is nested with the parent.

**Comment by WDaan** [comment]
Yes, you're absolutely right! The close behavior isn't as it should be.

The nested 'dialog' shouldn't be a problem? It's generated from a mixin, aren't these unique?

**Comment by m4ximuel** [comment]
Vuejs DevTools gave me a nested warning about 'dialog'.
I don't think it will be a problem even if we don't fix it, but it's uncomfortable.

**Pull request merged**
