### PR TITLE
perf: Rework search engine

### PR DESCRIPTION
**Pull request by Larsluph**
# Rework search engine [perf]

It's missing column filters to replicate the base WebUI if we want to be perfect but everything essential is there and working!

# PR Checklist

- [x] I've started from master
- [x] I've only committed changes related to this PR
- [x] All Unit tests pass
- [x] I've removed all commented code
- [x] I've removed all unneeded console.log statements

### CODE REVIEW

**Review by WDaan — COMMENTED** [review]
Awesome! Nice cleanup on the api side. What's holding this back?

**Comment by Larsluph** [comment]
> Awesome! Nice cleanup on the api side. What's holding this back?

Got some exams right now, I just need to take time to design the view

**Comment by WDaan** [comment]
No worries! Good luck 🤞

**Review by WDaan — APPROVED** [review]

**Comment by WDaan** [comment]
Awesome work! I really like the new plugin manager, super sleek. 🚀 

Only remark I can find is, on PWA mobile... the search table doesnt fit the screen so you still need to horizontolly scroll to be able to hit the download button. Don't really understand why as putting it on mobile screen size using devtools does not cause this issue.

Either way, great work! Huge improvement over the current one.

**Comment by Larsluph** [comment]
haha responsive design as always 😁, we have the problem on every other data table we're using, I think you can fix it using `width: 100%`. Will check that later to fix that on rss articles as well

**Pull request merged**
