### PR TITLE
Fix authentication race condition (#1285)

### LINKED ISSUE #1285: [Bug] Getting login screen even when logged in
Even if I'm logged in, I get a login screen while accessing the VueTorrent page. Going to the same address again fixes it. I don't get asked for logins across reloads.

[Here's a screen recording.](https://streamable.com/ympfhc)

### PR DESCRIPTION
**Pull request by KoHcoJlb**
Fixes #1285

### CODE REVIEW

**Comment by WDaan** [comment]
Could you explain the reasoning why this would solve the issue?

**Comment by KoHcoJlb** [comment]
Reasoning would be that this issue happens because of race condition when we check authentication
i.e. we start checking authentication asynchronously [here](https://github.com/WDaan/VueTorrent/blob/e1a9622da929855c0123afac5f429f9cbf3761d6/src/App.vue#L52), then while request is in flight we pass both authentication checks [here](https://github.com/WDaan/VueTorrent/blob/575b071f6db9edc01412fab45109d3f4d203552d/src/plugins/router.ts#L15) and [here](https://github.com/WDaan/VueTorrent/blob/master/src/pages/Login.vue#L56) while isAuthenticated is still false
This change allows Login component to catch when authentication check completes and drive login flow forward

**Comment by KoHcoJlb** [comment]
I've also tested this and can confirm that it solves the issue.

**Review by Larsluph — APPROVED** [review]
Awesome, thanks for the investigation and fix!

**Comment by WDaan** [comment]
Makes sense! Thanks for the investigation :)

**Review by WDaan — APPROVED** [review]

**Comment by KoHcoJlb** [comment]
Thank you back for this beautiful ui)

**Pull request merged**
