### PR TITLE
Create fr.js

### PR DESCRIPTION
**Pull request by Kaowain**
Add french translation (fr-fr)

# French translation [feature]
Add French (fr-fr) translation to the new lang file

# PR Checklist
- [x] I've started from master
- [x] I've only committed changes related to this PR
- [ ] All Unit tests pass
- [x] I've removed all commented code
- [x] I've removed all unneeded console.log statements

### CODE REVIEW

**Comment by Kaowain** [comment]
enjoy the french translation ;-)

**Comment by WDaan** [comment]
Great! thx 😄

**Comment by Kaowain** [comment]
what a rapid merge  :) thanks Daan! Enjoy it. Great works

**Comment by WDaan** [comment]
Looked great, so why wouldn't I 😀

**Pull request merged**
