### PR TITLE
navbar and more

### PR DESCRIPTION
**Pull request by m4ximuel**
# navbar and more [feat]
- New type of navigation button group design
- delete confirm modal deselects only when the torrent list is in edit mode
- Torrent details modal now can use torrent right click menu
- Minor functional improvements to the torrent right click menu
- Changed display design when there is no torrent list or searched item
- New selection mode design on the dashboard
- Close the torrent right click menu when the client is resized
- New pagenation design
- Automatic two columns for torrent list

# PR Checklist
- [x] I've started from master
- [x] I've only committed changes related to this PR
- [x] All Unit tests pass
- [ ] I've removed all commented code
- [x] I've removed all unneeded console.log statements

### CODE REVIEW

**Comment by m4ximuel** [comment]
@WDaan Completion writing

**Comment by WDaan** [comment]
I really like the end result but please keep changes in a single PR to a minimum.
I've added the `I've only committed changes related to this PR` checkbox, expecting changes like "Update searchbox" or "tweak context menu" but changing the whole navbar + some other things makes it really hard to verify and merges PR's like this.

Also I see a lot of dead code, you've 'replaced' the whole 'TopActions' compontent... but the component is still there. After a while we'll end up with a lot of dead code that's hard to distinguish from code that's still being used.

Finally the functionality of everything is exceptional! But working code is not enough, I try very hard to keep everything as clear and easy to understand as possible. Big components with gigantic functions may work absolutely fine, they are insanely hard to maintain & easy to break. I'd rather split up functionality into small compontens with small and easy functions.

Please understand that I'm not critiquing you, I just keep the best interests for the project in mind. I intend to maintain this for quite some time to come & I want everything to still be easy to understand in the future. Same goes for new people that would like to contribute to the project.

So please (in the future)
-  split up compontents into smaller chunks
- write short, self explanatory & easy to understand functions
- keep changes in a single PR to a minimum, those I can merge almost instantly

**Comment by m4ximuel** [comment]
@WDaan I worked with too much greed at once. I will work more clearly and distinctly. I have done most of the coding work personally, so I am not familiar with team work yet. sorry about that. I'll show you a better look next time.

**Comment by m4ximuel** [comment]
@WDaan Is it a good idea to take some time to fix this part? Or How about I'll PR the features one by one from the beginning? First of all, I hope think you this PR as a trial version of the direction I want to pursue.

**Comment by WDaan** [comment]
Hi! I really appreciate the work you're doing here :). Dont feel obligated to work on this, do it when you want.

Yes, seperate PR's would be nice. That way I can idependently merge changes more quickly. Like #255 
I was going to do it myself but I'm a little busy.

As I've said before, I really do like the end result & the direction you're heading in. It's just easier to merge smaller independent features without breaking anything. 🙂

**Comment by m4ximuel** [comment]
@WDaan For now, I will leave it as a sample and close it when it is determined that all features have been PR.

**Pull request closed without merging**
