### PR TITLE
chore: Update readme screenshots

### PR DESCRIPTION
**Pull request by Larsluph**
# Update readme screenshots [chore]

Update README screenshots

# PR Checklist

- [x] I've started from master
- [x] I've only committed changes related to this PR
- [x] All Unit tests pass
- [x] I've removed all commented code
- [x] I've removed all unneeded console.log statements

### CODE REVIEW

**Comment by WDaan** [comment]
Awsome! This was long overdue. It's cool to see how much the project has evolved over time :) 

Thx for all your contributions so far!

**Comment by WDaan** [comment]
@Larsluph Sizing is a bit  off though 😅

**Comment by Larsluph** [comment]
I tried putting mobile screenshots side-by-side but markdown is kind of limited on that 😅

**Comment by WDaan** [comment]
You can do html tags for images as well, which do allow resizing and putting side by side

**Pull request merged**
